-- =====================================================================
--  MDE Electromecánica · Sistema de Órdenes de Trabajo
--  Paso 1 de 3 · Esquema de la base de datos (Supabase / PostgreSQL)
--
--  Crea tablas, reglas (stock, numeración, avisos) y permisos por rol.
--  Se corre UNA sola vez, en un proyecto de Supabase vacío.
--  Si ya lo corriste, usá 00_verificar.sql para ver en qué paso seguir.
-- =====================================================================
do $$
begin
  if to_regtype('public.rol_usuario') is not null then
    raise exception 'Este paso ya está hecho: la base ya fue creada. Corré 00_verificar.sql para ver en qué paso seguir.';
  end if;
end $$;

begin;

-- ---------------------------------------------------------------------
-- 1. Listas fijas
-- ---------------------------------------------------------------------
create type public.rol_usuario      as enum ('ADMINISTRADOR', 'OFICINA', 'DEPOSITO', 'MECANICO');
create type public.tipo_unidad      as enum ('LIVIANA', 'PESADA', 'MINIBÚS');
create type public.estado_ot        as enum ('ABIERTA', 'EN DIAGNÓSTICO', 'EN REPARACIÓN',
                                             'ESPERANDO REPUESTOS', 'FINALIZADA', 'CERRADA', 'PRUEBA');
create type public.estado_tarea     as enum ('PENDIENTE', 'EN CURSO', 'PAUSADA', 'HECHA');
create type public.tipo_movimiento  as enum ('STOCK INICIAL', 'ENTRADA', 'SALIDA', 'AJUSTE');
create type public.estado_solicitud as enum ('PENDIENTE', 'APROBADA', 'RECHAZADA');

-- ---------------------------------------------------------------------
-- 2. Usuarios y roles
-- ---------------------------------------------------------------------
create table public.usuarios (
  id         uuid primary key references auth.users (id) on delete cascade,
  nombre     text not null,
  activo     boolean not null default true,
  creado_en  timestamptz not null default now()
);

create table public.usuario_roles (
  usuario_id uuid not null references public.usuarios (id) on delete cascade,
  rol        public.rol_usuario not null,
  primary key (usuario_id, rol)
);

-- Cada vez que se crea un usuario en Supabase (Authentication) se crea su ficha.
-- El nombre se toma de los datos del usuario ("nombre") o, si no hay, del email.
create or replace function public.crear_ficha_usuario()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.usuarios (id, nombre)
  values (new.id, coalesce(nullif(trim(new.raw_user_meta_data ->> 'nombre'), ''),
                           split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end $$;

create trigger al_crear_usuario
  after insert on auth.users
  for each row execute function public.crear_ficha_usuario();

-- ¿El usuario conectado tiene este rol?
create or replace function public.tiene_rol(r public.rol_usuario)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1
    from public.usuario_roles ur
    join public.usuarios u on u.id = ur.usuario_id
    where ur.usuario_id = auth.uid() and ur.rol = r and u.activo
  );
$$;

create or replace function public.es_admin()
returns boolean language sql stable as $$ select public.tiene_rol('ADMINISTRADOR') $$;

create or replace function public.es_oficina_o_admin()
returns boolean language sql stable as $$
  select public.tiene_rol('OFICINA') or public.tiene_rol('ADMINISTRADOR')
$$;

-- Administrador, Oficina y Depósito ven todas las OT; el mecánico solo las suyas.
create or replace function public.ve_todas_las_ot()
returns boolean language sql stable as $$
  select public.tiene_rol('ADMINISTRADOR') or public.tiene_rol('OFICINA') or public.tiene_rol('DEPOSITO')
$$;

-- ---------------------------------------------------------------------
-- 3. Configuración
-- ---------------------------------------------------------------------
create table public.configuracion (
  clave       text primary key,
  valor       text,
  descripcion text
);

-- ---------------------------------------------------------------------
-- 4. Clientes, marcas, modelos y unidades
-- ---------------------------------------------------------------------
create table public.clientes (
  id          bigint generated by default as identity primary key,
  nombre      text not null check (trim(nombre) <> ''),
  cuit        text,
  telefono    text,
  email       text,
  direccion   text,
  contacto    text,
  fecha_alta  date default current_date
);
create unique index clientes_nombre_unico on public.clientes (upper(trim(nombre)));

create table public.marcas (
  id      bigint generated by default as identity primary key,
  nombre  text not null
);
create unique index marcas_nombre_unico on public.marcas (upper(trim(nombre)));

create table public.modelos (
  id        bigint generated by default as identity primary key,
  marca_id  bigint not null references public.marcas (id) on delete cascade,
  nombre    text not null
);
create unique index modelos_nombre_unico on public.modelos (marca_id, upper(trim(nombre)));

create table public.unidades (
  id          bigint generated by default as identity primary key,
  cliente_id  bigint not null references public.clientes (id),
  interno     text,                                   -- INT (ej. 572, 6-489, MBS1001)
  dominio     text not null check (trim(dominio) <> ''),
  chasis      text,
  marca_id    bigint references public.marcas (id),
  modelo_id   bigint references public.modelos (id),
  tipo        public.tipo_unidad,                     -- se completa solo en la OT
  creado_en   timestamptz not null default now()
);
-- El dominio no puede repetirse (sin importar espacios ni mayúsculas).
create unique index unidades_dominio_unico on public.unidades (upper(regexp_replace(dominio, '\s+', '', 'g')));
create index unidades_cliente on public.unidades (cliente_id);

-- ---------------------------------------------------------------------
-- 5. Tempario
-- ---------------------------------------------------------------------
create table public.categorias_tempario (
  id      bigint generated by default as identity primary key,
  nombre  text not null check (trim(nombre) <> '')
);
create unique index categorias_nombre_unico on public.categorias_tempario (upper(trim(nombre)));

create table public.tempario (
  id            bigint generated by default as identity primary key,
  tipo          public.tipo_unidad not null,
  categoria_id  bigint not null references public.categorias_tempario (id),
  tarea         text not null check (trim(tarea) <> ''),
  horas         numeric(6,2) not null check (horas > 0),
  activo        boolean not null default true,
  creado_por    uuid references public.usuarios (id),
  creado_en     timestamptz not null default now()
);
-- Sin duplicados: la misma tarea no se repite dentro del mismo tipo y categoría
-- (la misma tarea sí puede estar en frenos delanteros y en frenos traseros).
create unique index tempario_sin_duplicados
  on public.tempario (tipo, categoria_id, upper(trim(tarea)));

-- ---------------------------------------------------------------------
-- 6. Repuestos
-- ---------------------------------------------------------------------
create table public.repuestos (
  codigo        text primary key check (trim(codigo) <> ''),
  descripcion   text not null,
  -- Código sin espacios: así el escáner lo encuentra con o sin espacio.
  codigo_limpio text generated always as (upper(regexp_replace(codigo, '\s+', '', 'g'))) stored,
  creado_en     timestamptz not null default now()
);
create unique index repuestos_codigo_limpio on public.repuestos (codigo_limpio);

-- Busca un repuesto por código escaneado o escrito (ignora espacios y mayúsculas).
create or replace function public.buscar_repuesto(p_codigo text)
returns setof public.repuestos language sql stable as $$
  select * from public.repuestos
  where codigo_limpio = upper(regexp_replace(coalesce(p_codigo, ''), '\s+', '', 'g'));
$$;

-- ---------------------------------------------------------------------
-- 7. Órdenes de trabajo y sus tareas
-- ---------------------------------------------------------------------
create table public.ordenes_trabajo (
  id              bigint generated by default as identity primary key,
  numero          integer not null unique,             -- se asigna solo (correlativo)
  estado          public.estado_ot not null default 'ABIERTA',
  fecha_ingreso   date not null default current_date,  -- automática; queda fija
  hora_ingreso    time,
  fecha_salida    date,                                -- a mano
  hora_salida     time,
  presupuesto     text,
  ot_cliente      text,
  nro_factura     text,
  cliente_id      bigint not null references public.clientes (id),
  unidad_id       bigint not null references public.unidades (id),
  km              integer not null check (km >= 0),
  tipo            public.tipo_unidad not null,
  observaciones   text,
  creado_por      uuid references public.usuarios (id),
  creado_en       timestamptz not null default now(),
  actualizado_en  timestamptz not null default now()
);
create index ot_unidad on public.ordenes_trabajo (unidad_id);
create index ot_estado on public.ordenes_trabajo (estado);

create table public.tareas_ot (
  id           bigint generated by default as identity primary key,
  ot_id        bigint not null references public.ordenes_trabajo (id) on delete cascade,
  renglon      integer,                                -- se numera solo dentro de la OT
  tempario_id  bigint references public.tempario (id) on delete set null,
  descripcion  text,                                   -- si viene del tempario se completa sola
  horas        numeric(6,2) check (horas >= 0),        -- horas del tempario (lo que se cobra)
  estado       public.estado_tarea not null default 'PENDIENTE',
  creado_en    timestamptz not null default now()
);
create index tareas_ot_ot on public.tareas_ot (ot_id);

-- Mecánicos de cada tarea: uno, o dos en casos puntuales.
create table public.asignaciones (
  tarea_id      bigint not null references public.tareas_ot (id) on delete cascade,
  mecanico_id   uuid not null references public.usuarios (id),
  asignado_en   timestamptz not null default now(),
  terminada_en  timestamptz,                           -- cuando ESTE mecánico termina su parte
  primary key (tarea_id, mecanico_id)
);
create index asignaciones_mecanico on public.asignaciones (mecanico_id);

-- Repuestos usados en la OT (descuentan stock).
create table public.repuestos_ot (
  id             bigint generated by default as identity primary key,
  ot_id          bigint not null references public.ordenes_trabajo (id) on delete cascade,
  tarea_id       bigint references public.tareas_ot (id) on delete set null,
  codigo         text not null references public.repuestos (codigo) on update cascade,
  cantidad       numeric(12,2) not null check (cantidad > 0),   -- admite decimales (litros)
  cargado_por    uuid references public.usuarios (id) default auth.uid(),
  cargado_en     timestamptz not null default now(),
  modificado_por uuid references public.usuarios (id),
  modificado_en  timestamptz
);
create index repuestos_ot_ot on public.repuestos_ot (ot_id);
create index repuestos_ot_tarea on public.repuestos_ot (tarea_id);

-- ---------------------------------------------------------------------
-- 8. Stock (movimientos)
-- ---------------------------------------------------------------------
-- El stock disponible no se guarda: es la suma de los movimientos.
--   STOCK INICIAL, ENTRADA  → suman      SALIDA → resta      AJUSTE → suma o resta
create table public.movimientos_stock (
  id              bigint generated by default as identity primary key,
  fecha           timestamptz not null default now(),
  tipo            public.tipo_movimiento not null,
  codigo          text not null references public.repuestos (codigo) on update cascade,
  cantidad        numeric(12,2) not null,
  ot_id           bigint references public.ordenes_trabajo (id) on delete cascade,
  repuesto_ot_id  bigint unique references public.repuestos_ot (id) on delete cascade,
  usuario_id      uuid references public.usuarios (id) default auth.uid(),
  usuario_nombre  text,          -- solo para movimientos traídos del Excel
  observacion     text,          -- remito, proveedor o motivo
  constraint cantidad_valida check (
    (tipo = 'AJUSTE' and cantidad <> 0) or (tipo <> 'AJUSTE' and cantidad > 0)
  )
);
create index movimientos_codigo on public.movimientos_stock (codigo);

-- Número legible para mensajes: 2.50 → "2,5", 10.00 → "10"
create or replace function public.num_texto(v numeric)
returns text language sql immutable as $$
  select replace(case when position('.' in v::text) > 0
                      then rtrim(rtrim(v::text, '0'), '.') else v::text end, '.', ',');
$$;

create or replace function public.stock_de(p_codigo text)
returns numeric language sql stable security definer set search_path = public as $$
  select coalesce(sum(case tipo when 'SALIDA' then -cantidad else cantidad end), 0)
  from public.movimientos_stock where codigo = p_codigo;
$$;

create view public.stock_disponible with (security_invoker = true) as
select r.codigo,
       r.descripcion,
       coalesce(sum(m.cantidad) filter (where m.tipo = 'STOCK INICIAL'), 0) as stock_inicial,
       coalesce(sum(m.cantidad) filter (where m.tipo = 'ENTRADA'), 0)       as entradas,
       coalesce(sum(m.cantidad) filter (where m.tipo = 'SALIDA'), 0)        as salidas,
       coalesce(sum(m.cantidad) filter (where m.tipo = 'AJUSTE'), 0)        as ajustes,
       coalesce(sum(case m.tipo when 'SALIDA' then -m.cantidad else m.cantidad end), 0) as disponible
from public.repuestos r
left join public.movimientos_stock m on m.codigo = r.codigo
group by r.codigo, r.descripcion;

-- ---------------------------------------------------------------------
-- 9. Tiempos reales (control interno)
-- ---------------------------------------------------------------------
create table public.registros_tiempo (
  id           bigint generated by default as identity primary key,
  tarea_id     bigint not null references public.tareas_ot (id) on delete cascade,
  mecanico_id  uuid not null references public.usuarios (id),
  inicio       timestamptz not null default now(),
  fin          timestamptz,
  check (fin is null or fin >= inicio)
);
-- Un mecánico no puede tener dos cronómetros abiertos en la misma tarea.
create unique index un_cronometro_abierto
  on public.registros_tiempo (tarea_id, mecanico_id) where fin is null;

create view public.horas_reales with (security_invoker = true) as
select rt.tarea_id,
       t.ot_id,
       rt.mecanico_id,
       u.nombre as mecanico,
       round(sum(extract(epoch from (coalesce(rt.fin, now()) - rt.inicio))) / 3600.0, 2) as horas_reales,
       bool_or(rt.fin is null) as en_curso
from public.registros_tiempo rt
join public.tareas_ot t on t.id = rt.tarea_id
join public.usuarios u on u.id = rt.mecanico_id
group by rt.tarea_id, t.ot_id, rt.mecanico_id, u.nombre;

-- ---------------------------------------------------------------------
-- 10. Solicitudes de tareas nuevas y avisos
-- ---------------------------------------------------------------------
create table public.solicitudes (
  id               bigint generated by default as identity primary key,
  ot_id            bigint not null references public.ordenes_trabajo (id) on delete cascade,
  tarea_origen_id  bigint references public.tareas_ot (id) on delete set null,
  mecanico_id      uuid not null default auth.uid() references public.usuarios (id),
  falla            text not null check (trim(falla) <> ''),
  tarea_propuesta  text not null check (trim(tarea_propuesta) <> ''),
  tempario_id      bigint references public.tempario (id),
  estado           public.estado_solicitud not null default 'PENDIENTE',
  motivo_rechazo   text,
  resuelta_por     uuid references public.usuarios (id),
  resuelta_en      timestamptz,
  tarea_creada_id  bigint references public.tareas_ot (id) on delete set null,
  creado_en        timestamptz not null default now(),
  constraint rechazo_con_motivo check (estado <> 'RECHAZADA' or coalesce(trim(motivo_rechazo), '') <> '')
);
create index solicitudes_ot on public.solicitudes (ot_id);

create table public.avisos (
  id            bigint generated by default as identity primary key,
  para_rol      public.rol_usuario,
  para_usuario  uuid references public.usuarios (id) on delete cascade,
  tipo          text not null,
  mensaje       text not null,
  ot_id         bigint references public.ordenes_trabajo (id) on delete cascade,
  creado_por    uuid references public.usuarios (id) default auth.uid(),
  creado_en     timestamptz not null default now(),
  leido         boolean not null default false,
  constraint aviso_con_destino check (para_rol is not null or para_usuario is not null)
);
create index avisos_usuario on public.avisos (para_usuario) where not leido;
create index avisos_rol on public.avisos (para_rol) where not leido;

-- =====================================================================
-- REGLAS AUTOMÁTICAS
-- =====================================================================

-- Número de OT con prefijo (ej. OT-001401)
create or replace function public.numero_ot_texto(p_numero integer)
returns text language sql stable security definer set search_path = public as $$
  select coalesce((select valor from public.configuracion where clave = 'prefijo_ot'), '')
         || lpad(p_numero::text, 6, '0');
$$;

-- OT: número correlativo, cliente desde la unidad, fecha de ingreso fija.
create or replace function public.antes_de_guardar_ot()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_inicial integer;
begin
  if tg_op = 'INSERT' then
    if new.numero is null then
      perform pg_advisory_xact_lock(hashtext('numero_ot'));
      select nullif(valor, '')::integer into v_inicial
        from public.configuracion where clave = 'nro_ot_inicial';
      select greatest(coalesce(max(numero), 0) + 1, coalesce(v_inicial, 1))
        into new.numero from public.ordenes_trabajo;
    end if;
    select cliente_id into new.cliente_id from public.unidades where id = new.unidad_id;
    new.creado_por := coalesce(new.creado_por, auth.uid());
  else
    -- La fecha de ingreso queda congelada (solo el Administrador puede corregirla).
    if new.fecha_ingreso is distinct from old.fecha_ingreso and not public.es_admin() then
      new.fecha_ingreso := old.fecha_ingreso;
    end if;
    if new.unidad_id is distinct from old.unidad_id then
      select cliente_id into new.cliente_id from public.unidades where id = new.unidad_id;
    end if;
    new.actualizado_en := now();
  end if;
  return new;
end $$;

create trigger ot_antes_de_guardar
  before insert or update on public.ordenes_trabajo
  for each row execute function public.antes_de_guardar_ot();

-- La unidad recuerda su tipo: si todavía no lo tenía, lo toma de la OT.
create or replace function public.recordar_tipo_unidad()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.unidades set tipo = new.tipo where id = new.unidad_id and tipo is null;
  return new;
end $$;

create trigger ot_recordar_tipo
  after insert on public.ordenes_trabajo
  for each row execute function public.recordar_tipo_unidad();

-- Tarea: renglón automático; descripción y horas desde el tempario.
create or replace function public.antes_de_guardar_tarea()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_tarea text; v_horas numeric;
begin
  if new.tempario_id is not null then
    select tarea, horas into v_tarea, v_horas from public.tempario where id = new.tempario_id;
    new.descripcion := coalesce(nullif(trim(new.descripcion), ''), v_tarea);
    new.horas := coalesce(new.horas, v_horas);
  end if;
  new.horas := coalesce(new.horas, 0);
  if coalesce(trim(new.descripcion), '') = '' then
    raise exception 'La tarea necesita una descripción';
  end if;
  if tg_op = 'INSERT' and new.renglon is null then
    select coalesce(max(renglon), 0) + 1 into new.renglon from public.tareas_ot where ot_id = new.ot_id;
  end if;
  return new;
end $$;

create trigger tarea_antes_de_guardar
  before insert or update on public.tareas_ot
  for each row execute function public.antes_de_guardar_tarea();

-- Asignación: solo usuarios con rol Mecánico, y como máximo dos por tarea.
create or replace function public.controlar_asignacion()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.usuario_roles where usuario_id = new.mecanico_id and rol = 'MECANICO') then
    raise exception 'Solo se pueden asignar usuarios con rol Mecánico';
  end if;
  if (select count(*) from public.asignaciones where tarea_id = new.tarea_id and mecanico_id <> new.mecanico_id) >= 2 then
    raise exception 'Una tarea puede tener como máximo dos mecánicos';
  end if;
  return new;
end $$;

create trigger asignacion_controlar
  before insert or update on public.asignaciones
  for each row execute function public.controlar_asignacion();

-- Repuesto en OT: controla stock (si no alcanza, no deja cargar).
create or replace function public.controlar_stock_repuesto_ot()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_disponible numeric; v_ot bigint;
begin
  if new.tarea_id is not null then
    select ot_id into v_ot from public.tareas_ot where id = new.tarea_id;
    if v_ot is distinct from new.ot_id then
      raise exception 'La tarea no pertenece a esa OT';
    end if;
  end if;
  -- Bloquea el repuesto para que dos cargas simultáneas no pasen el stock.
  perform 1 from public.repuestos where codigo = new.codigo for update;
  v_disponible := public.stock_de(new.codigo);
  if tg_op = 'UPDATE' and old.codigo = new.codigo then
    v_disponible := v_disponible + old.cantidad;
  end if;
  if new.cantidad > v_disponible then
    raise exception 'Stock insuficiente de %: disponible %, pedido %',
      new.codigo, public.num_texto(v_disponible), public.num_texto(new.cantidad)
      using errcode = 'P0001', hint = 'STOCK_INSUFICIENTE';
  end if;
  if tg_op = 'UPDATE' then
    new.modificado_por := auth.uid();
    new.modificado_en := now();
  end if;
  return new;
end $$;

create trigger repuesto_ot_controlar_stock
  before insert or update on public.repuestos_ot
  for each row execute function public.controlar_stock_repuesto_ot();

-- Repuesto en OT: genera la SALIDA de stock; si se corrige o se borra, el stock vuelve.
-- Si quien modifica o quita no es Oficina ni Administrador, avisa a ambos.
create or replace function public.movimiento_repuesto_ot()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_desc text; v_numero integer; v_nombre text;
begin
  if tg_op = 'INSERT' then
    insert into public.movimientos_stock (tipo, codigo, cantidad, ot_id, repuesto_ot_id, usuario_id)
    values ('SALIDA', new.codigo, new.cantidad, new.ot_id, new.id, auth.uid());
    return new;
  end if;

  select numero into v_numero from public.ordenes_trabajo where id = coalesce(new.ot_id, old.ot_id);
  select nombre into v_nombre from public.usuarios where id = auth.uid();

  if tg_op = 'UPDATE' then
    update public.movimientos_stock
       set codigo = new.codigo, cantidad = new.cantidad
     where repuesto_ot_id = new.id;
    if not public.es_oficina_o_admin() and (new.cantidad <> old.cantidad or new.codigo <> old.codigo) then
      select descripcion into v_desc from public.repuestos where codigo = new.codigo;
      insert into public.avisos (para_rol, tipo, mensaje, ot_id)
      select r, 'REPUESTO MODIFICADO',
             format('%s modificó un repuesto en %s: %s (%s), cantidad %s → %s',
                    coalesce(v_nombre, 'Un usuario'), public.numero_ot_texto(v_numero),
                    v_desc, new.codigo, public.num_texto(old.cantidad), public.num_texto(new.cantidad)),
             new.ot_id
      from unnest(array['OFICINA', 'ADMINISTRADOR']::public.rol_usuario[]) r;
    end if;
    return new;
  end if;

  -- DELETE: el movimiento de salida se borra solo (el stock vuelve).
  if not public.es_oficina_o_admin() and auth.uid() is not null then
    select descripcion into v_desc from public.repuestos where codigo = old.codigo;
    insert into public.avisos (para_rol, tipo, mensaje, ot_id)
    select r, 'REPUESTO QUITADO',
           format('%s quitó un repuesto de %s: %s (%s), cantidad %s',
                  coalesce(v_nombre, 'Un usuario'), public.numero_ot_texto(v_numero),
                  v_desc, old.codigo, public.num_texto(old.cantidad)),
           old.ot_id
    from unnest(array['OFICINA', 'ADMINISTRADOR']::public.rol_usuario[]) r
    where exists (select 1 from public.ordenes_trabajo where id = old.ot_id);
  end if;
  return old;
end $$;

create trigger repuesto_ot_movimiento
  after insert or update or delete on public.repuestos_ot
  for each row execute function public.movimiento_repuesto_ot();

-- Solicitud nueva: avisa a Oficina.
create or replace function public.avisar_solicitud_nueva()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_numero integer; v_nombre text;
begin
  select numero into v_numero from public.ordenes_trabajo where id = new.ot_id;
  select nombre into v_nombre from public.usuarios where id = new.mecanico_id;
  insert into public.avisos (para_rol, tipo, mensaje, ot_id)
  values ('OFICINA', 'SOLICITUD NUEVA',
          format('%s pide agregar a %s: %s', coalesce(v_nombre, 'Un mecánico'),
                 public.numero_ot_texto(v_numero), new.tarea_propuesta),
          new.ot_id);
  return new;
end $$;

create trigger solicitud_avisar
  after insert on public.solicitudes
  for each row execute function public.avisar_solicitud_nueva();

-- =====================================================================
-- ACCIONES (las usa la app)
-- =====================================================================

-- Crear una OT con sus tareas y repuestos en un solo paso.
-- Obligatorio: unidad (cliente y dominio), KM, tipo y al menos una tarea o un repuesto.
--   p_tareas:    [{"tempario_id": 12}, {"descripcion": "Tarea a mano", "horas": 1.5}]
--   p_repuestos: [{"codigo": "A9061800109", "cantidad": 2}]
create or replace function public.crear_ot(
  p_unidad_id     bigint,
  p_km            integer,
  p_tipo          public.tipo_unidad,
  p_tareas        jsonb default '[]'::jsonb,
  p_repuestos     jsonb default '[]'::jsonb,
  p_observaciones text default null,
  p_presupuesto   text default null,
  p_ot_cliente    text default null,
  p_hora_ingreso  time default null
) returns bigint language plpgsql security invoker set search_path = public as $$
declare v_ot bigint; t jsonb; r jsonb;
begin
  if not public.es_oficina_o_admin() then
    raise exception 'Solo Oficina o Administrador pueden crear OT';
  end if;
  if p_unidad_id is null or p_km is null or p_tipo is null then
    raise exception 'Faltan datos obligatorios: unidad, KM y tipo de unidad';
  end if;
  if coalesce(jsonb_array_length(p_tareas), 0) + coalesce(jsonb_array_length(p_repuestos), 0) = 0 then
    raise exception 'La OT necesita al menos un trabajo o un repuesto';
  end if;

  insert into public.ordenes_trabajo (unidad_id, km, tipo, observaciones, presupuesto, ot_cliente, hora_ingreso)
  values (p_unidad_id, p_km, p_tipo, p_observaciones, p_presupuesto, p_ot_cliente, p_hora_ingreso)
  returning id into v_ot;

  for t in select * from jsonb_array_elements(coalesce(p_tareas, '[]'::jsonb)) loop
    insert into public.tareas_ot (ot_id, tempario_id, descripcion, horas)
    values (v_ot, (t ->> 'tempario_id')::bigint, t ->> 'descripcion', (t ->> 'horas')::numeric);
  end loop;

  for r in select * from jsonb_array_elements(coalesce(p_repuestos, '[]'::jsonb)) loop
    insert into public.repuestos_ot (ot_id, codigo, cantidad)
    values (v_ot, r ->> 'codigo', (r ->> 'cantidad')::numeric);
  end loop;

  return v_ot;
end $$;

-- Cronómetro del mecánico: iniciar / pausar / terminar su parte de la tarea.
create or replace function public.iniciar_tarea(p_tarea_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.asignaciones where tarea_id = p_tarea_id and mecanico_id = auth.uid()) then
    raise exception 'Esta tarea no está asignada a vos';
  end if;
  if exists (select 1 from public.tareas_ot where id = p_tarea_id and estado = 'HECHA') then
    raise exception 'La tarea ya está terminada';
  end if;
  insert into public.registros_tiempo (tarea_id, mecanico_id)
  values (p_tarea_id, auth.uid())
  on conflict do nothing;
  update public.asignaciones set terminada_en = null where tarea_id = p_tarea_id and mecanico_id = auth.uid();
  update public.tareas_ot set estado = 'EN CURSO' where id = p_tarea_id;
end $$;

create or replace function public.pausar_tarea(p_tarea_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  update public.registros_tiempo set fin = now()
   where tarea_id = p_tarea_id and mecanico_id = auth.uid() and fin is null;
  -- Si nadie más está trabajando en la tarea, queda en pausa.
  if not exists (select 1 from public.registros_tiempo where tarea_id = p_tarea_id and fin is null) then
    update public.tareas_ot set estado = 'PAUSADA' where id = p_tarea_id and estado = 'EN CURSO';
  end if;
end $$;

-- Con dos mecánicos, la tarea queda HECHA cuando terminan los dos.
create or replace function public.terminar_tarea(p_tarea_id bigint)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not exists (select 1 from public.asignaciones where tarea_id = p_tarea_id and mecanico_id = auth.uid()) then
    raise exception 'Esta tarea no está asignada a vos';
  end if;
  update public.registros_tiempo set fin = now()
   where tarea_id = p_tarea_id and mecanico_id = auth.uid() and fin is null;
  update public.asignaciones set terminada_en = now()
   where tarea_id = p_tarea_id and mecanico_id = auth.uid();
  if not exists (select 1 from public.asignaciones where tarea_id = p_tarea_id and terminada_en is null) then
    update public.tareas_ot set estado = 'HECHA' where id = p_tarea_id;
  elsif not exists (select 1 from public.registros_tiempo where tarea_id = p_tarea_id and fin is null) then
    update public.tareas_ot set estado = 'PAUSADA' where id = p_tarea_id;
  end if;
end $$;

-- Oficina aprueba una solicitud: crea la tarea en la OT y, si se indica, la asigna.
create or replace function public.aprobar_solicitud(p_solicitud_id bigint, p_mecanicos uuid[] default null)
returns bigint language plpgsql security definer set search_path = public as $$
declare s public.solicitudes; v_tarea bigint; m uuid; v_numero integer;
begin
  if not public.es_oficina_o_admin() then
    raise exception 'Solo Oficina o Administrador pueden aprobar solicitudes';
  end if;
  select * into s from public.solicitudes where id = p_solicitud_id for update;
  if s.id is null or s.estado <> 'PENDIENTE' then
    raise exception 'La solicitud no existe o ya fue resuelta';
  end if;
  insert into public.tareas_ot (ot_id, tempario_id, descripcion)
  values (s.ot_id, s.tempario_id, case when s.tempario_id is null then s.tarea_propuesta end)
  returning id into v_tarea;
  foreach m in array coalesce(p_mecanicos, array[]::uuid[]) loop
    insert into public.asignaciones (tarea_id, mecanico_id) values (v_tarea, m);
  end loop;
  update public.solicitudes
     set estado = 'APROBADA', resuelta_por = auth.uid(), resuelta_en = now(), tarea_creada_id = v_tarea
   where id = s.id;
  select numero into v_numero from public.ordenes_trabajo where id = s.ot_id;
  insert into public.avisos (para_usuario, tipo, mensaje, ot_id)
  values (s.mecanico_id, 'SOLICITUD APROBADA',
          format('Se aprobó tu solicitud en %s: %s', public.numero_ot_texto(v_numero), s.tarea_propuesta),
          s.ot_id);
  return v_tarea;
end $$;

-- Oficina rechaza una solicitud: el motivo es obligatorio y le llega al mecánico.
create or replace function public.rechazar_solicitud(p_solicitud_id bigint, p_motivo text)
returns void language plpgsql security definer set search_path = public as $$
declare s public.solicitudes; v_numero integer;
begin
  if not public.es_oficina_o_admin() then
    raise exception 'Solo Oficina o Administrador pueden rechazar solicitudes';
  end if;
  if coalesce(trim(p_motivo), '') = '' then
    raise exception 'Escribí el motivo del rechazo';
  end if;
  select * into s from public.solicitudes where id = p_solicitud_id for update;
  if s.id is null or s.estado <> 'PENDIENTE' then
    raise exception 'La solicitud no existe o ya fue resuelta';
  end if;
  update public.solicitudes
     set estado = 'RECHAZADA', motivo_rechazo = p_motivo, resuelta_por = auth.uid(), resuelta_en = now()
   where id = s.id;
  select numero into v_numero from public.ordenes_trabajo where id = s.ot_id;
  insert into public.avisos (para_usuario, tipo, mensaje, ot_id)
  values (s.mecanico_id, 'SOLICITUD RECHAZADA',
          format('Se rechazó tu solicitud en %s: %s. Motivo: %s',
                 public.numero_ot_texto(v_numero), s.tarea_propuesta, p_motivo),
          s.ot_id);
end $$;

-- Stock disponible de un repuesto (para el mecánico al escanear).
create or replace function public.consultar_stock(p_codigo text)
returns table (codigo text, descripcion text, disponible numeric)
language sql stable security definer set search_path = public as $$
  select r.codigo, r.descripcion, public.stock_de(r.codigo)
  from public.repuestos r
  where r.codigo_limpio = upper(regexp_replace(coalesce(p_codigo, ''), '\s+', '', 'g'));
$$;

-- =====================================================================
-- PERMISOS POR ROL (Row Level Security)
-- =====================================================================
-- Funciones auxiliares para el mecánico
create or replace function public.mecanico_en_tarea(p_tarea_id bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.asignaciones where tarea_id = p_tarea_id and mecanico_id = auth.uid());
$$;

create or replace function public.mecanico_en_ot(p_ot_id bigint)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.asignaciones a join public.tareas_ot t on t.id = a.tarea_id
    where t.ot_id = p_ot_id and a.mecanico_id = auth.uid()
  );
$$;

alter table public.usuarios            enable row level security;
alter table public.usuario_roles       enable row level security;
alter table public.configuracion       enable row level security;
alter table public.clientes            enable row level security;
alter table public.marcas              enable row level security;
alter table public.modelos             enable row level security;
alter table public.unidades            enable row level security;
alter table public.categorias_tempario enable row level security;
alter table public.tempario            enable row level security;
alter table public.repuestos           enable row level security;
alter table public.ordenes_trabajo     enable row level security;
alter table public.tareas_ot           enable row level security;
alter table public.asignaciones        enable row level security;
alter table public.repuestos_ot        enable row level security;
alter table public.movimientos_stock   enable row level security;
alter table public.registros_tiempo    enable row level security;
alter table public.solicitudes         enable row level security;
alter table public.avisos              enable row level security;

-- Usuarios y roles: todos ven los nombres; solo el Administrador los gestiona.
create policy ver on public.usuarios for select to authenticated using (true);
create policy gestionar on public.usuarios for all to authenticated using (public.es_admin()) with check (public.es_admin());
create policy ver on public.usuario_roles for select to authenticated using (true);
create policy gestionar on public.usuario_roles for all to authenticated using (public.es_admin()) with check (public.es_admin());

-- Configuración: todos leen; el Administrador cambia.
create policy ver on public.configuracion for select to authenticated using (true);
create policy gestionar on public.configuracion for all to authenticated using (public.es_admin()) with check (public.es_admin());

-- Clientes, marcas, modelos y unidades: todos leen; Oficina y Administrador cargan.
create policy ver on public.clientes for select to authenticated using (true);
create policy gestionar on public.clientes for all to authenticated using (public.es_oficina_o_admin()) with check (public.es_oficina_o_admin());
create policy ver on public.marcas for select to authenticated using (true);
create policy gestionar on public.marcas for all to authenticated using (public.es_oficina_o_admin()) with check (public.es_oficina_o_admin());
create policy ver on public.modelos for select to authenticated using (true);
create policy gestionar on public.modelos for all to authenticated using (public.es_oficina_o_admin()) with check (public.es_oficina_o_admin());
create policy ver on public.unidades for select to authenticated using (true);
create policy gestionar on public.unidades for all to authenticated using (public.es_oficina_o_admin()) with check (public.es_oficina_o_admin());

-- Tempario: todos leen; solo el Administrador agrega o modifica servicios.
create policy ver on public.categorias_tempario for select to authenticated using (true);
create policy gestionar on public.categorias_tempario for all to authenticated using (public.es_admin()) with check (public.es_admin());
create policy ver on public.tempario for select to authenticated using (true);
create policy gestionar on public.tempario for all to authenticated using (public.es_admin()) with check (public.es_admin());

-- Repuestos: todos leen; Depósito y Administrador cargan.
create policy ver on public.repuestos for select to authenticated using (true);
create policy gestionar on public.repuestos for all to authenticated
  using (public.tiene_rol('DEPOSITO') or public.es_admin())
  with check (public.tiene_rol('DEPOSITO') or public.es_admin());

-- OT: Administrador, Oficina y Depósito ven todas; el mecánico, las suyas.
create policy ver on public.ordenes_trabajo for select to authenticated
  using (public.ve_todas_las_ot() or public.mecanico_en_ot(id));
create policy crear on public.ordenes_trabajo for insert to authenticated with check (public.es_oficina_o_admin());
create policy modificar on public.ordenes_trabajo for update to authenticated
  using (public.es_oficina_o_admin()) with check (public.es_oficina_o_admin());
create policy borrar on public.ordenes_trabajo for delete to authenticated using (public.es_admin());

-- Tareas: el mecánico ve solo las asignadas; las cambia con el cronómetro.
create policy ver on public.tareas_ot for select to authenticated
  using (public.ve_todas_las_ot() or public.mecanico_en_tarea(id));
create policy gestionar on public.tareas_ot for all to authenticated
  using (public.es_oficina_o_admin()) with check (public.es_oficina_o_admin());

create policy ver on public.asignaciones for select to authenticated
  using (public.ve_todas_las_ot() or mecanico_id = auth.uid() or public.mecanico_en_tarea(tarea_id));
create policy gestionar on public.asignaciones for all to authenticated
  using (public.es_oficina_o_admin()) with check (public.es_oficina_o_admin());

-- Repuestos de la OT: el mecánico carga, modifica y quita en sus tareas.
create policy ver on public.repuestos_ot for select to authenticated
  using (public.ve_todas_las_ot() or public.mecanico_en_tarea(tarea_id));
create policy cargar on public.repuestos_ot for insert to authenticated
  with check (public.es_oficina_o_admin() or public.tiene_rol('DEPOSITO')
              or (tarea_id is not null and public.mecanico_en_tarea(tarea_id)));
create policy modificar on public.repuestos_ot for update to authenticated
  using (public.ve_todas_las_ot() or public.mecanico_en_tarea(tarea_id))
  with check (public.ve_todas_las_ot() or public.mecanico_en_tarea(tarea_id));
create policy quitar on public.repuestos_ot for delete to authenticated
  using (public.ve_todas_las_ot() or public.mecanico_en_tarea(tarea_id));

-- Movimientos de stock: Depósito, Oficina y Administrador ven; Depósito y
-- Administrador cargan entradas, ajustes y stock inicial (las salidas son automáticas).
create policy ver on public.movimientos_stock for select to authenticated using (public.ve_todas_las_ot());
create policy cargar on public.movimientos_stock for insert to authenticated
  with check ((public.tiene_rol('DEPOSITO') or public.es_admin())
              and tipo <> 'SALIDA' and repuesto_ot_id is null);
create policy corregir on public.movimientos_stock for update to authenticated
  using (public.es_admin() and repuesto_ot_id is null)
  with check (public.es_admin() and tipo <> 'SALIDA' and repuesto_ot_id is null);
create policy borrar on public.movimientos_stock for delete to authenticated
  using (public.es_admin() and repuesto_ot_id is null);

-- Horas reales: solo el Administrador ve todas; cada mecánico ve las suyas.
create policy ver on public.registros_tiempo for select to authenticated
  using (public.es_admin() or mecanico_id = auth.uid());
create policy corregir on public.registros_tiempo for all to authenticated
  using (public.es_admin()) with check (public.es_admin());

-- Solicitudes: el mecánico crea en sus OT y ve las suyas; Oficina y Administrador ven todas.
create policy ver on public.solicitudes for select to authenticated
  using (public.es_oficina_o_admin() or mecanico_id = auth.uid());
create policy crear on public.solicitudes for insert to authenticated
  with check (mecanico_id = auth.uid() and public.mecanico_en_ot(ot_id));

-- Avisos: cada uno ve los suyos (por usuario o por rol) y los marca como leídos.
create policy ver on public.avisos for select to authenticated
  using (para_usuario = auth.uid() or (para_rol is not null and public.tiene_rol(para_rol)));
create policy marcar_leido on public.avisos for update to authenticated
  using (para_usuario = auth.uid() or (para_rol is not null and public.tiene_rol(para_rol)))
  with check (para_usuario = auth.uid() or (para_rol is not null and public.tiene_rol(para_rol)));

-- Accesos: nada para visitantes sin sesión; todo pasa por las reglas de arriba.
revoke all on all tables in schema public from anon;
revoke all on all functions in schema public from anon, public;
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on all functions in schema public to authenticated;
-- Las funciones de reglas internas no se llaman desde la app.
revoke execute on function public.crear_ficha_usuario() from authenticated;

-- Actualización en vivo: la app se entera al instante de cambios en estas tablas.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table
      public.ordenes_trabajo, public.tareas_ot, public.asignaciones,
      public.repuestos_ot, public.solicitudes, public.avisos;
  end if;
end $$;

commit;

select 'Paso 1 listo: esquema creado. Seguí con 02_datos_base.sql' as resultado;
