-- =====================================================================
--  MDE Electromecánica · Sistema de Órdenes de Trabajo
--  Paso 9 · Butacas: en las tareas de butacas se marca en el plano
--  qué butaca se trabajó y qué se le hizo.
--   - Butacas: COND (conductor) y 1 a 19 (minibús 19+1, de adelante hacia atrás).
--   - Cada butaca marcada suma 1 a la cantidad de la tarea (multiplica las horas).
--   - Si lo carga un mecánico, se avisa a Oficina y Administrador.
--  Se puede correr más de una vez sin problema.
-- =====================================================================
begin;

create table if not exists public.butacas_tarea (
  id          bigint generated by default as identity primary key,
  tarea_id    bigint not null references public.tareas_ot (id) on delete cascade,
  butaca      text not null check (butaca ~ '^(COND|[1-9]|1[0-9])$'),
  trabajos    text[] not null check (cardinality(trabajos) > 0 and trabajos <@ array['REEMPLAZO', 'REPARACION',
                'CAMBIO DE REPUESTO', 'COLOCACION DE CINTO', 'REEMPLAZO DE CINTO']),
  cargado_por uuid references public.usuarios (id),
  cargado_en  timestamptz not null default now(),
  unique (tarea_id, butaca)
);

-- Texto para mostrar los trabajos de una butaca.
create or replace function public.texto_trabajos_butaca(p text[])
returns text language sql immutable as $$
  select string_agg(case x when 'REEMPLAZO' then 'reemplazo de butaca' when 'REPARACION' then 'reparación'
                           when 'CAMBIO DE REPUESTO' then 'cambio de repuesto' when 'COLOCACION DE CINTO' then 'colocación de cinto'
                           when 'REEMPLAZO DE CINTO' then 'reemplazo de cinto' else lower(x) end, ', ')
  from unnest(p) x;
$$;

-- Guarda las butacas de una tarea (reemplaza las anteriores).
-- p_butacas: [{"butaca": "3", "trabajos": ["REPARACION", "REEMPLAZO DE CINTO"]}, ...]
create or replace function public.guardar_butacas(p_tarea_id bigint, p_butacas jsonb)
returns integer language plpgsql security definer set search_path = public as $$
declare v_t public.tareas_ot; v_estado public.estado_ot; v_numero integer; v_previas integer; v_n integer;
        r jsonb; v_nombre text; v_lista text;
begin
  select * into v_t from public.tareas_ot where id = p_tarea_id for update;
  if v_t.id is null then raise exception 'La tarea no existe'; end if;
  if not (public.mecanico_en_tarea(p_tarea_id) or public.es_oficina_o_admin()) then
    raise exception 'No tenés permiso para cargar butacas en esta tarea';
  end if;
  select estado, numero into v_estado, v_numero from public.ordenes_trabajo where id = v_t.ot_id;
  if v_estado in ('CERRADA', 'PRUEBA') then
    raise exception 'La OT está cerrada: no se pueden hacer cambios';
  end if;

  select count(*) into v_previas from public.butacas_tarea where tarea_id = p_tarea_id;
  delete from public.butacas_tarea where tarea_id = p_tarea_id;
  for r in select * from jsonb_array_elements(coalesce(p_butacas, '[]'::jsonb)) loop
    if jsonb_array_length(coalesce(r -> 'trabajos', '[]'::jsonb)) = 0 then
      raise exception 'Indicá qué se le hizo a la butaca %', r ->> 'butaca';
    end if;
    insert into public.butacas_tarea (tarea_id, butaca, trabajos, cargado_por)
    values (p_tarea_id, upper(trim(r ->> 'butaca')),
            array(select x from (select distinct jsonb_array_elements_text(r -> 'trabajos') as x) d
                  order by array_position(array['REEMPLAZO', 'REPARACION', 'CAMBIO DE REPUESTO',
                                                'COLOCACION DE CINTO', 'REEMPLAZO DE CINTO'], x)),
            auth.uid());
  end loop;

  -- Cada butaca suma 1 a la cantidad (si se borran todas, vuelve a 1).
  select count(*) into v_n from public.butacas_tarea where tarea_id = p_tarea_id;
  if v_n > 0 then
    update public.tareas_ot set cantidad = v_n where id = p_tarea_id and cantidad <> v_n;
  elsif v_previas > 0 then
    update public.tareas_ot set cantidad = 1 where id = p_tarea_id and cantidad <> 1;
  end if;

  if not public.es_oficina_o_admin() then
    select nombre into v_nombre from public.usuarios where id = auth.uid();
    select string_agg(case butaca when 'COND' then 'conductor' else butaca end || ': ' || public.texto_trabajos_butaca(trabajos), '; '
                      order by case butaca when 'COND' then 0 else butaca::int end)
      into v_lista from public.butacas_tarea where tarea_id = p_tarea_id;
    insert into public.avisos (para_rol, tipo, mensaje, ot_id, creado_por)
    select x, 'BUTACAS',
           format('%s marcó %s butaca%s en %s (%s)%s. Cantidad de la tarea: %s', coalesce(v_nombre, 'Un mecánico'),
                  v_n, case when v_n = 1 then '' else 's' end, public.numero_ot_texto(v_numero), v_t.descripcion,
                  coalesce(': ' || v_lista, ''), case when v_n > 0 then v_n else 1 end),
           v_t.ot_id, auth.uid()
    from unnest(array['OFICINA', 'ADMINISTRADOR']::public.rol_usuario[]) x;
  end if;
  return v_n;
end $$;

alter table public.butacas_tarea enable row level security;
drop policy if exists ver on public.butacas_tarea;
create policy ver on public.butacas_tarea for select to authenticated
  using (public.ve_todas_las_ot() or public.mecanico_en_tarea(tarea_id));
revoke all on public.butacas_tarea from anon;
grant select on public.butacas_tarea to authenticated;
revoke execute on function public.guardar_butacas(bigint, jsonb) from public, anon;
grant execute on function public.guardar_butacas(bigint, jsonb) to authenticated;

commit;

select 'Paso 9 listo: butacas' as resultado;
