-- =====================================================================
--  MDE Electromecánica · Sistema de Órdenes de Trabajo
--  Paso 10 · El mecánico ve todas las OT del taller (solo consulta) y pide tareas sin asignar
--   - ots_taller(estado): OT de ese estado con sus tareas y quién las tiene, más la cantidad por estado.
--   - ot_taller(id): una OT con sus tareas (sin repuestos ni horas reales).
--   - pedir_tarea(tarea): el mecánico pide una tarea sin asignar; avisa a Oficina y Administrador.
--   - resolver_pedido_tarea(pedido, aprobar, motivo): Oficina o Administrador; al aprobar queda asignada.
--  Se puede correr más de una vez sin problema.
-- =====================================================================
begin;

create table if not exists public.pedidos_tarea (
  id           bigint generated by default as identity primary key,
  tarea_id     bigint not null references public.tareas_ot (id) on delete cascade,
  mecanico_id  uuid not null references public.usuarios (id),
  ot_id        bigint references public.ordenes_trabajo (id) on delete cascade,
  ot_numero    integer,
  descripcion  text,
  dominio      text,
  estado       text not null default 'PENDIENTE' check (estado in ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
  motivo       text,
  creado_en    timestamptz not null default now(),
  resuelto_por uuid references public.usuarios (id),
  resuelto_en  timestamptz
);
create unique index if not exists pedidos_tarea_pendiente on public.pedidos_tarea (tarea_id, mecanico_id) where estado = 'PENDIENTE';

-- Una OT con sus tareas, para la vista del mecánico (uso interno).
create or replace function public.ot_taller_json(p_ot_id bigint)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    'id', o.id, 'numero', o.numero, 'estado', o.estado, 'tipo', o.tipo, 'fecha_ingreso', o.fecha_ingreso,
    'km', o.km, 'observaciones', o.observaciones, 'dominio', u.dominio, 'interno', u.interno,
    'cliente', c.nombre, 'marca', ma.nombre, 'modelo', mo.nombre,
    'pausa', (select p.motivo from public.pausas_ot p where p.ot_id = o.id and p.fin is null limit 1),
    'tareas', coalesce((select jsonb_agg(jsonb_build_object(
        'id', t.id, 'renglon', t.renglon, 'descripcion', t.descripcion, 'estado', t.estado, 'cantidad', t.cantidad,
        'asignados', coalesce((select jsonb_agg(us.nombre order by us.nombre)
                                 from public.asignaciones a join public.usuarios us on us.id = a.mecanico_id
                                where a.tarea_id = t.id), '[]'::jsonb),
        'mia', exists (select 1 from public.asignaciones a where a.tarea_id = t.id and a.mecanico_id = auth.uid()),
        'pedida', exists (select 1 from public.pedidos_tarea pt where pt.tarea_id = t.id
                           and pt.mecanico_id = auth.uid() and pt.estado = 'PENDIENTE')
      ) order by t.renglon) from public.tareas_ot t where t.ot_id = o.id), '[]'::jsonb))
  from public.ordenes_trabajo o
  left join public.unidades u on u.id = o.unidad_id
  left join public.clientes c on c.id = o.cliente_id
  left join public.marcas ma on ma.id = u.marca_id
  left join public.modelos mo on mo.id = u.modelo_id
  where o.id = p_ot_id;
$$;

create or replace function public.ots_taller(p_estado text)
returns jsonb language plpgsql stable security definer set search_path = public as $$
begin
  if not public.tiene_algun_rol() then raise exception 'No tenés permiso'; end if;
  return jsonb_build_object(
    'conteos', coalesce((select jsonb_object_agg(estado, n)
                           from (select estado::text as estado, count(*) as n from public.ordenes_trabajo group by estado) x), '{}'::jsonb),
    'ots', coalesce((select jsonb_agg(public.ot_taller_json(s.id) order by s.numero desc)
                       from (select id, numero from public.ordenes_trabajo where estado::text = p_estado
                              order by numero desc limit 150) s), '[]'::jsonb));
end $$;

create or replace function public.ot_taller(p_ot_id bigint)
returns jsonb language plpgsql stable security definer set search_path = public as $$
begin
  if not public.tiene_algun_rol() then raise exception 'No tenés permiso'; end if;
  return public.ot_taller_json(p_ot_id);
end $$;

-- El mecánico pide hacer una tarea que no tiene a nadie asignado.
create or replace function public.pedir_tarea(p_tarea_id bigint)
returns bigint language plpgsql security definer set search_path = public as $$
declare v_t public.tareas_ot; v_ot public.ordenes_trabajo; v_dominio text; v_nombre text; v_id bigint;
begin
  if not public.tiene_rol('MECANICO') then raise exception 'Solo los mecánicos pueden pedir tareas'; end if;
  select * into v_t from public.tareas_ot where id = p_tarea_id for update;
  if v_t.id is null then raise exception 'La tarea no existe'; end if;
  select * into v_ot from public.ordenes_trabajo where id = v_t.ot_id;
  if v_ot.estado in ('FINALIZADA', 'CERRADA', 'PRUEBA') then
    raise exception 'La OT está finalizada o cerrada: no se pueden pedir tareas';
  end if;
  if v_t.estado = 'HECHA' then raise exception 'La tarea ya está hecha'; end if;
  if exists (select 1 from public.asignaciones where tarea_id = p_tarea_id) then
    raise exception 'La tarea ya tiene un mecánico asignado';
  end if;
  if exists (select 1 from public.pedidos_tarea where tarea_id = p_tarea_id and mecanico_id = auth.uid() and estado = 'PENDIENTE') then
    raise exception 'Ya pediste esta tarea: espera la aprobación';
  end if;
  select dominio into v_dominio from public.unidades where id = v_ot.unidad_id;
  insert into public.pedidos_tarea (tarea_id, mecanico_id, ot_id, ot_numero, descripcion, dominio)
  values (p_tarea_id, auth.uid(), v_ot.id, v_ot.numero, v_t.descripcion, v_dominio)
  returning id into v_id;
  select nombre into v_nombre from public.usuarios where id = auth.uid();
  insert into public.avisos (para_rol, tipo, mensaje, ot_id, creado_por)
  select x, 'PEDIDO DE TAREA',
         format('%s pide hacer "%s" en %s (%s)', coalesce(v_nombre, 'Un mecánico'), v_t.descripcion,
                public.numero_ot_texto(v_ot.numero), v_dominio),
         v_ot.id, auth.uid()
  from unnest(array['OFICINA', 'ADMINISTRADOR']::public.rol_usuario[]) x;
  return v_id;
end $$;

-- Oficina o Administrador aprueban (queda asignada) o rechazan con motivo.
create or replace function public.resolver_pedido_tarea(p_id bigint, p_aprobar boolean, p_motivo text default null)
returns void language plpgsql security definer set search_path = public as $$
declare v public.pedidos_tarea; v_estado public.estado_ot; v_nombre text; r record;
begin
  if not public.es_oficina_o_admin() then raise exception 'Solo Oficina o Administrador pueden resolver pedidos de tareas'; end if;
  select * into v from public.pedidos_tarea where id = p_id for update;
  if v.id is null or v.estado <> 'PENDIENTE' then raise exception 'El pedido no existe o ya fue resuelto'; end if;
  if p_aprobar then
    select o.estado into v_estado from public.tareas_ot t join public.ordenes_trabajo o on o.id = t.ot_id where t.id = v.tarea_id;
    if v_estado in ('FINALIZADA', 'CERRADA', 'PRUEBA') then
      raise exception 'La OT está finalizada o cerrada: no se puede asignar';
    end if;
    insert into public.asignaciones (tarea_id, mecanico_id) values (v.tarea_id, v.mecanico_id) on conflict do nothing;
    update public.pedidos_tarea set estado = 'APROBADO', resuelto_por = auth.uid(), resuelto_en = now() where id = p_id;
    insert into public.avisos (para_usuario, tipo, mensaje, ot_id)
    values (v.mecanico_id, 'TAREA ASIGNADA',
            format('Te asignaron "%s" en %s (%s)', v.descripcion, public.numero_ot_texto(v.ot_numero), v.dominio), v.ot_id);
    -- Los demás que la habían pedido quedan rechazados.
    select nombre into v_nombre from public.usuarios where id = v.mecanico_id;
    for r in
      update public.pedidos_tarea
         set estado = 'RECHAZADO', motivo = 'Se le asignó a ' || coalesce(v_nombre, 'otro mecánico'),
             resuelto_por = auth.uid(), resuelto_en = now()
       where tarea_id = v.tarea_id and estado = 'PENDIENTE' and id <> p_id
      returning mecanico_id
    loop
      insert into public.avisos (para_usuario, tipo, mensaje, ot_id)
      values (r.mecanico_id, 'PEDIDO DE TAREA RECHAZADO',
              format('No se te asignó "%s" en %s: se le asignó a %s', v.descripcion,
                     public.numero_ot_texto(v.ot_numero), coalesce(v_nombre, 'otro mecánico')), v.ot_id);
    end loop;
  else
    if nullif(trim(p_motivo), '') is null then raise exception 'Escribí el motivo del rechazo'; end if;
    update public.pedidos_tarea set estado = 'RECHAZADO', motivo = trim(p_motivo), resuelto_por = auth.uid(), resuelto_en = now()
     where id = p_id;
    insert into public.avisos (para_usuario, tipo, mensaje, ot_id)
    values (v.mecanico_id, 'PEDIDO DE TAREA RECHAZADO',
            format('No se aprobó tu pedido de "%s" en %s: %s', v.descripcion, public.numero_ot_texto(v.ot_numero), trim(p_motivo)),
            v.ot_id);
  end if;
end $$;

-- Si Oficina asigna directamente al mecánico que la había pedido, su pedido queda aprobado.
create or replace function public.aprobar_pedido_al_asignar()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.pedidos_tarea set estado = 'APROBADO', resuelto_por = auth.uid(), resuelto_en = now()
   where tarea_id = new.tarea_id and mecanico_id = new.mecanico_id and estado = 'PENDIENTE';
  return new;
end $$;
drop trigger if exists asignacion_aprueba_pedido on public.asignaciones;
create trigger asignacion_aprueba_pedido
  after insert on public.asignaciones
  for each row execute function public.aprobar_pedido_al_asignar();

alter table public.pedidos_tarea enable row level security;
drop policy if exists ver on public.pedidos_tarea;
create policy ver on public.pedidos_tarea for select to authenticated
  using (mecanico_id = auth.uid() or public.es_oficina_o_admin());
revoke all on public.pedidos_tarea from anon;
grant select on public.pedidos_tarea to authenticated;

revoke execute on function public.ot_taller_json(bigint), public.aprobar_pedido_al_asignar() from public, anon, authenticated;
revoke execute on function public.ots_taller(text), public.ot_taller(bigint), public.pedir_tarea(bigint),
  public.resolver_pedido_tarea(bigint, boolean, text) from public, anon;
grant execute on function public.ots_taller(text), public.ot_taller(bigint), public.pedir_tarea(bigint),
  public.resolver_pedido_tarea(bigint, boolean, text) to authenticated;

commit;

select 'Paso 10 listo: OT del taller para el mecánico' as resultado;
