-- =====================================================================
--  MDE Electromecánica · Sistema de Órdenes de Trabajo
--  Paso 11 · Registro de la OT (solo Administrador)
--   - Nuevo motivo de pausa: COMIDA.
--   - historial_ot: guarda cada cambio de estado, de fecha de ingreso y de salida (quién y cuándo).
--   - registro_ot(ot): todo lo que pasó en la OT, en orden: creación, estados, pausas (desde/hasta),
--     tramos de trabajo de cada mecánico, asignaciones, repuestos, pedidos y solicitudes.
--   - reporte_pausas(desde, hasta): todas las pausas del período con su duración.
--  Se puede correr más de una vez sin problema.
-- =====================================================================

-- Va fuera de la transacción: el valor nuevo tiene que quedar guardado antes de usarlo.
alter type public.motivo_pausa add value if not exists 'COMIDA' before 'OTRO';

begin;

create table if not exists public.historial_ot (
  id          bigint generated by default as identity primary key,
  ot_id       bigint not null references public.ordenes_trabajo (id) on delete cascade,
  tipo        text not null,
  detalle     text,
  usuario_id  uuid references public.usuarios (id),
  creado_en   timestamptz not null default now()
);
create index if not exists historial_ot_ot on public.historial_ot (ot_id, creado_en);

create or replace function public.registrar_cambio_ot()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.estado is distinct from old.estado then
    insert into public.historial_ot (ot_id, tipo, detalle, usuario_id)
    values (new.id, 'ESTADO', old.estado || ' → ' || new.estado, auth.uid());
  end if;
  if new.fecha_ingreso is distinct from old.fecha_ingreso or new.hora_ingreso is distinct from old.hora_ingreso then
    insert into public.historial_ot (ot_id, tipo, detalle, usuario_id)
    values (new.id, 'INGRESO',
            format('Cambió la fecha de ingreso: %s → %s',
                   concat_ws(' ', to_char(old.fecha_ingreso, 'DD/MM/YYYY'), to_char(old.hora_ingreso, 'HH24:MI')),
                   concat_ws(' ', to_char(new.fecha_ingreso, 'DD/MM/YYYY'), to_char(new.hora_ingreso, 'HH24:MI'))), auth.uid());
  end if;
  if new.fecha_salida is distinct from old.fecha_salida or new.hora_salida is distinct from old.hora_salida then
    insert into public.historial_ot (ot_id, tipo, detalle, usuario_id)
    values (new.id, 'SALIDA',
            case when new.fecha_salida is null then 'Se borró la fecha de salida'
                 else 'Fecha de salida: ' || concat_ws(' ', to_char(new.fecha_salida, 'DD/MM/YYYY'), to_char(new.hora_salida, 'HH24:MI')) end,
            auth.uid());
  end if;
  return new;
end $$;

drop trigger if exists ot_registrar_cambio on public.ordenes_trabajo;
create trigger ot_registrar_cambio
  after update on public.ordenes_trabajo
  for each row execute function public.registrar_cambio_ot();

-- Todo lo que pasó en una OT, en orden. Solo Administrador.
create or replace function public.registro_ot(p_ot_id bigint)
returns table (momento timestamptz, hasta timestamptz, tipo text, detalle text, usuario text)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.es_admin() then raise exception 'Solo el Administrador puede ver el registro'; end if;
  return query
  select * from (
    -- Creación
    select o.creado_en, null::timestamptz, 'OT CREADA'::text,
           format('Ingreso %s%s · KM %s', to_char(o.fecha_ingreso, 'DD/MM/YYYY'), coalesce(' ' || to_char(o.hora_ingreso, 'HH24:MI'), ''), o.km)
             || coalesce(' · pedida por ' || sol.nombre, ''),
           cre.nombre
      from public.ordenes_trabajo o
      left join public.usuarios cre on cre.id = o.creado_por
      left join public.usuarios sol on sol.id = o.solicitada_por
     where o.id = p_ot_id
    union all
    -- Cambios de estado y de fechas
    select h.creado_en, null, h.tipo, h.detalle, u.nombre
      from public.historial_ot h left join public.usuarios u on u.id = h.usuario_id
     where h.ot_id = p_ot_id
    union all
    -- Pausas de la OT (desde / hasta)
    select p.inicio, p.fin, 'PAUSA',
           public.texto_motivo(p.motivo) || coalesce(': ' || nullif(trim(p.detalle), ''), '')
             || case when p.fin is null then ' · sigue pausada' else coalesce(' · reanudó ' || re.nombre, '') end,
           pa.nombre
      from public.pausas_ot p
      left join public.usuarios pa on pa.id = p.pausada_por
      left join public.usuarios re on re.id = p.reanudada_por
     where p.ot_id = p_ot_id
    union all
    -- Tramos de trabajo de cada mecánico (cronómetro)
    select r.inicio, r.fin, 'TRABAJO', t.renglon || '. ' || t.descripcion, u.nombre
      from public.registros_tiempo r
      join public.tareas_ot t on t.id = r.tarea_id
      left join public.usuarios u on u.id = r.mecanico_id
     where t.ot_id = p_ot_id
    union all
    -- Asignaciones y tareas terminadas
    select a.asignado_en, null, 'ASIGNACIÓN', t.renglon || '. ' || t.descripcion, u.nombre
      from public.asignaciones a join public.tareas_ot t on t.id = a.tarea_id left join public.usuarios u on u.id = a.mecanico_id
     where t.ot_id = p_ot_id
    union all
    select a.terminada_en, null, 'TAREA TERMINADA', t.renglon || '. ' || t.descripcion, u.nombre
      from public.asignaciones a join public.tareas_ot t on t.id = a.tarea_id left join public.usuarios u on u.id = a.mecanico_id
     where t.ot_id = p_ot_id and a.terminada_en is not null
    union all
    -- Repuestos
    select ro.cargado_en, null, 'REPUESTO CARGADO',
           coalesce(rp.descripcion, ro.codigo) || ' (' || ro.codigo || ') x ' || public.num_texto(ro.cantidad), u.nombre
      from public.repuestos_ot ro left join public.repuestos rp on rp.codigo = ro.codigo left join public.usuarios u on u.id = ro.cargado_por
     where ro.ot_id = p_ot_id
    union all
    select ro.entregado_en, null, 'REPUESTO ENTREGADO',
           coalesce(rp.descripcion, ro.codigo) || ' x ' || public.num_texto(ro.cantidad), u.nombre
      from public.repuestos_ot ro left join public.repuestos rp on rp.codigo = ro.codigo left join public.usuarios u on u.id = ro.entregado_por
     where ro.ot_id = p_ot_id and ro.entregado_en is not null
    union all
    select pr.creado_en, pr.resuelto_en, 'PEDIDO DE REPUESTO',
           pr.descripcion || ' x ' || public.num_texto(pr.cantidad)
             || case when pr.estado = 'RESUELTO' then ' · resuelto por ' || coalesce(rs.nombre, '') else ' · pendiente' end,
           u.nombre
      from public.pedidos_repuesto pr left join public.usuarios u on u.id = pr.pedido_por left join public.usuarios rs on rs.id = pr.resuelto_por
     where pr.ot_id = p_ot_id
    union all
    -- Solicitudes de tareas nuevas y pedidos de tareas sin asignar
    select s.creado_en, s.resuelta_en, 'TAREA SOLICITADA',
           s.tarea_propuesta || ' (falla: ' || s.falla || ') · ' || lower(s.estado::text)
             || coalesce(' por ' || rs.nombre, '') || coalesce(': ' || s.motivo_rechazo, ''),
           u.nombre
      from public.solicitudes s left join public.usuarios u on u.id = s.mecanico_id left join public.usuarios rs on rs.id = s.resuelta_por
     where s.ot_id = p_ot_id
    union all
    select pt.creado_en, pt.resuelto_en, 'PIDIÓ TAREA',
           pt.descripcion || ' · ' || lower(pt.estado) || coalesce(' por ' || rs.nombre, '') || coalesce(': ' || pt.motivo, ''),
           u.nombre
      from public.pedidos_tarea pt left join public.usuarios u on u.id = pt.mecanico_id left join public.usuarios rs on rs.id = pt.resuelto_por
     where pt.ot_id = p_ot_id
  ) x
  order by 1, 3;
end $$;

-- Todas las pausas del período (por fecha de inicio, hora de Argentina). Solo Administrador.
create or replace function public.reporte_pausas(p_desde date, p_hasta date)
returns table (ot_id bigint, ot_numero integer, dominio text, cliente text, motivo text, detalle text,
               pauso text, reanudo text, inicio timestamptz, fin timestamptz, minutos numeric)
language plpgsql stable security definer set search_path = public as $$
begin
  if not public.es_admin() then raise exception 'Solo el Administrador puede ver este reporte'; end if;
  return query
  select o.id, o.numero, u.dominio, c.nombre, public.texto_motivo(p.motivo), p.detalle,
         pa.nombre, re.nombre, p.inicio, p.fin,
         round((extract(epoch from (coalesce(p.fin, now()) - p.inicio)) / 60)::numeric, 0)
    from public.pausas_ot p
    join public.ordenes_trabajo o on o.id = p.ot_id
    left join public.unidades u on u.id = o.unidad_id
    left join public.clientes c on c.id = o.cliente_id
    left join public.usuarios pa on pa.id = p.pausada_por
    left join public.usuarios re on re.id = p.reanudada_por
   where (p.inicio at time zone 'America/Argentina/Buenos_Aires')::date between p_desde and p_hasta
   order by p.inicio;
end $$;

alter table public.historial_ot enable row level security;
drop policy if exists ver on public.historial_ot;
create policy ver on public.historial_ot for select to authenticated using (public.es_admin());
revoke all on public.historial_ot from anon;
grant select on public.historial_ot to authenticated;

revoke execute on function public.registrar_cambio_ot() from public, anon, authenticated;
revoke execute on function public.registro_ot(bigint), public.reporte_pausas(date, date) from public, anon;
grant execute on function public.registro_ot(bigint), public.reporte_pausas(date, date) to authenticated;

commit;

select 'Paso 11 listo: registro de la OT' as resultado;
